language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36-django-21
    - python: 3.7
      env: TOXENV=py37-django-21

install:
  - pip install pipenv
  - pipenv install --dev
script:
  - tox
