language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36-django-22
    - python: 3.7
      dist: xenial
      sudo: yes
      env: TOXENV=py37-django-22
    - python: 3.6
      env: TOXENV=readme

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install coverage coveralls
script:
  - tox
after_success:
  - coverage combine
  - coveralls
