# Generated by Django 2.1.2 on 2018-11-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerfest', '0005_alter_beer_abv_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbeer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userbeer',
            name='tried',
        ),
    ]
