# Generated by Django 2.1.2 on 2018-11-12 15:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    StarBeer = apps.get_model("beerfest", "StarBeer")
    StarBeer.objects.filter(starred=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('beerfest', '0007_auto_20181112_0844'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='starbeer',
            name='starred',
        ),
    ]
