# Generated by Django 2.1.7 on 2019-02-15 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beerfest', '0009_auto_20181112_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='rated_by',
            field=models.ManyToManyField(related_name='rated_beers', through='beerfest.BeerRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beer',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_beers', through='beerfest.StarBeer', to=settings.AUTH_USER_MODEL),
        ),
    ]
