# Generated by Django 2.2.6 on 2019-10-10 05:08

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('beerfest', '0010_auto_20190215_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['bar', 'brewery__name', django.db.models.expressions.OrderBy(django.db.models.expressions.F('number'), nulls_last=True), 'name']},
        ),
        migrations.AlterModelOptions(
            name='brewery',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together={('brewery', 'name', 'bar', 'number')},
        ),
    ]
